name: recipy2
description: a social recipe app to keep track of new dishes, and share with friends.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.3.1
  provider: ^6.0.2
  flutter_colorpicker: ^1.0.3
  intl: ^0.17.0
  uuid: ^3.0.6
  smooth_page_indicator: ^1.0.0+2
  webview_flutter: ^3.0.1
  url_launcher: ^6.0.20
  shared_preferences: ^2.0.13
  cached_network_image: ^3.2.0
  flutter_slidable: ^1.2.1
  flutter_svg: ^1.0.3
  json_annotation: ^4.5.0
  chopper: ^4.0.5
  logging: ^1.0.2








  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
  json_serializable: ^6.2.0
  chopper_generator: ^4.0.5




flutter:
  uses-material-design: true
  assets:
    - assets/recipes1.json
    - assets/recipes2.json
    - assets/images/

